"""initial schema

Revision ID: 33058d26709e
Revises: 
Create Date: 2026-07-14 03:45:13.914069

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('emotions',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('symbols',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lens_meanings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('auth_provider', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), server_default='ru', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("locale in ('ru','kk','en')", name='ck_users_locale'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dreams',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('sleep_quality', sa.SmallInteger(), nullable=True),
    sa.Column('is_lucid', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sleep_quality is null or sleep_quality between 1 and 5', name='ck_dreams_sleep_quality'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patterns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurrences', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_notified', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type in ('recurring_symbol','emotion_trend','cycle')", name='ck_patterns_type'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('default_lens', sa.String(), server_default='psych', nullable=False),
    sa.Column('onboarding', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('wake_time', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(), server_default='Asia/Almaty', nullable=False),
    sa.CheckConstraint("default_lens in ('psych','classic','ibn_sirin','science')", name='ck_profiles_default_lens'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('streaks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('longest', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_entry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rc_customer_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("plan in ('monthly','annual','lifetime')", name='ck_subscriptions_plan'),
    sa.CheckConstraint("status in ('trial','active','expired','grace')", name='ck_subscriptions_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_quota',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('interpretations_used', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('chat_questions_used', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'day')
    )
    op.create_table('dream_embeddings',
    sa.Column('dream_id', sa.UUID(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dream_id')
    )
    op.create_table('dream_emotions',
    sa.Column('dream_id', sa.UUID(), nullable=False),
    sa.Column('emotion_id', sa.SmallInteger(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.CheckConstraint("kind in ('in_dream','on_waking')", name='ck_dream_emotions_kind'),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dream_id', 'emotion_id', 'kind')
    )
    op.create_table('dream_symbols',
    sa.Column('dream_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('salience', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dream_id', 'symbol_id')
    )
    op.create_table('interpretations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dream_id', sa.UUID(), nullable=False),
    sa.Column('lens', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("lens in ('psych','classic','ibn_sirin','science')", name='ck_interpretations_lens'),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_cards',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dream_id', sa.UUID(), nullable=False),
    sa.Column('template', sa.String(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('share_cards')
    op.drop_table('interpretations')
    op.drop_table('dream_symbols')
    op.drop_table('dream_emotions')
    op.drop_table('dream_embeddings')
    op.drop_table('usage_quota')
    op.drop_table('subscriptions')
    op.drop_table('streaks')
    op.drop_table('profiles')
    op.drop_table('patterns')
    op.drop_table('dreams')
    op.drop_table('users')
    op.drop_table('symbols')
    op.drop_table('emotions')
    # ### end Alembic commands ###
